### ISSUE TITLE
Load Field Details button not working

### ISSUE THREAD

**Issue by jeasterday2** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#24]
No response is received from the Load Field Details button.  I am attempting to decrease the compile size of a formula so need this to determine where I can reduce size

**Comment by kpeterson85** [comment]
@jeasterday2 Can you provide a screenshot of the formula editor and what your page looks like when the issue is occurring?  Also, can you check the chrome developer tools console log to see if any javascript errors are showing after you've clicked Load Field Details?

**Comment by JNelz** [comment]
I'm getting the same issue. 

This is a screenshot of the errors when the page initially loads. Clicking on the button gives no response and does not add any errors to the already existing ones on the developer tools console.  

![Screen Shot 2019-08-22 at 10 54 54 AM](https://user-images.githubusercontent.com/54382541/63478034-567dc900-c4cb-11e9-9909-7d2de7d90401.png)

A second screenshot after turning off a few other plugins seems to provide something more meaningful. Again, on page load, nothing is additionally added when the button is clicked. 

![Screen Shot 2019-08-22 at 11 04 55 AM](https://user-images.githubusercontent.com/54382541/63478405-0ef83c80-c4cd-11e9-905b-fcedcae3d3e8.png)

It appears to work on other objects, like Account, but not on the Service Appointment.

**Comment by kpeterson85** [comment]
@JNelz Thank you for providing the screenshots. You mentioned it works for Account but not for Service Appointment.  Does it work for many other objects (standard and custom), just not Service Appointment? That could point to something unique with that object.  The error appears to be occurring when trying to look up the fields for the object.

**Comment by JNelz** [comment]
@kpeterson85 , it seems to work fine on objects like Contact and Opportunity as well, but not on Product Consumed, Product Request, etc. It might be something specific to the Field Service Lightning standard objects, potentially?

**Comment by curtmgray** [comment]
I'm reproducing this on a custom object in my org as well. I can see the button but upon clicking it nothing seems to happen. I also don't see the fields for what record I want it to load the fields from.

**Comment by kpeterson85** [comment]
After some digging I found that the meta data requests target a specific API version and this version number hasn't been updated in a long time so I'm thinking newer standard objects like Service Appointment or custom objects that reference newer standard objects could be erroring because it can't even see these newer objects.  I will make updates to target the newer API versions and to also display a clear error message when a specific object can't be described.

**Comment by kpeterson85** [comment]
@jeasterday2 @JNelz @curtmgray I've published an updated version that should work with the newer standard objects like Service Appointment.  The new extension version is 1.5.4.  Your chrome should have auto updated it for you but you can confirm from the manage extensions page in chrome what version you have.  Could you then try editing your formulas again and confirm you can load the field details?  If there is an issue still, the new version should at least present it better rather than not loading anything.

**Comment by curtmgray** [comment]
Good update! That seemed to fix things for me!

As a quick side note I noticed, awhile back I unsubscribed from paying for the plugin. I had intended to resubscribe at some point but forgot. It looks like doing that left me stuck with an earlier version of the plugin (1.5.2) I needed to buy back in to get the access to the update. Not sure if that's something you can detect from your side of things, I wonder if I would have avoided the issue entirely if I had been subscribed at the time?
