### ISSUE TITLE
Yellow message about needing a new subscription license key

### ISSUE THREAD

**Issue by eleazarcorilla** [kpeterson85/Salesforce-Enhanced-Formula-Editor-Chrome-Extension#32]
I received the below message in the extension. How do I create a new subscription?

![subscription license key message](https://user-images.githubusercontent.com/105022/104218000-185baf00-540a-11eb-9130-ee2a1646db7e.png)

**Comment by kpeterson85** [comment]
Hi @eleazarcorilla, thank you for reaching out about this new message.

Your existing subscription was created through Google but they are doing away with their Chrome extension payment system which is why I've had to make updates to move to a new service (Stripe). You can see and manage your existing Google subscription by visiting https://pay.google.com/ while logged in with the Google account you set up your subscription with.

Based on the information Google published in their deprecation announcement (https://developer.chrome.com/docs/webstore/cws-payments-deprecation/), Google will disable your existing Google subscription payment on 2/1/2021.

To create the new subscription you can click the "Get a License Key" button that is in the yellow message box shown in your screenshot. It will take you to the Install page (https://www.enhancedformulaeditor.com/install.php) on my website that provides you the steps for how to set up the new subscription.

If you have questions about your specific subscription and need to provide me any personal details, please email me at kyle.p.developer@gmail.com.

I apologize for this extra hassle as Google moves providers off of their system.

**Comment by eleazarcorilla** [comment]
If I remember it correctly, my initial subscription was 28 Dkk for the
whole year. Now it is x4 surge so is it correct that it is now more or less
120 dkk or 20 usd per year?

**Comment by kpeterson85** [comment]
@eleazarcorilla Yes the extension at one time was $5 a year but years later was increased to $20 a year.
